spring.application.name=task

spring.docker.compose.lifecycle-management=start_only

spring.sql.init.mode=always
spring.datasource.url=jdbc:postgresql://localhost:5433/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
